### ISSUE TITLE
Need to add function.csv to vul.tar.gz

### ISSUE THREAD

**Issue by darkskytechnology** [facebookresearch/nbref#5]
$ python preprocess/vul_preprocess.py
...
FileNotFoundError: [Errno 2] No such file or directory: 'data/vul/function.csv'

Can you please add the csv file to the vulnerability data that can be downloaded directly?

**Comment by MCCTT** [comment]
Changing lines 45:64 of vul_preprocess.py to:

```
def load_graphs(args):
    #csv_file = os.path.join(args.csv_dir, "function.csv")
    json_file = os.path.join(args.csv_dir, "function.json") 
    paths = []
    #df = pd.read_csv(csv_file, header=0, index_col=False)
    df = pd.read_json(json_file)
    id2sha = df.to_dict()['commit_id']
    id2tgt = df.to_dict()['target']
    idx = [str(i) for i in id2sha.keys()]

        
    #with open(os.path.join(args.file_list), "r") as f:
    #    idx = [str(i.strip()) for i in f.readlines()]

    for i in range(0, len(idx)):
        id = idx[i]
        path = os.path.join(args.asm_dir, str(id)+ "_" + id2sha[int(id)] + ".s")
        if os.path.isfile(path):
            paths.append(
                (i, path, id2tgt[int(id)]))

    graphs_asm = {}
    large_asm  = {}
    tgt_asm = {}
```

worked for me (the data is there is just a json instead of a csv)

**Comment by ChengFu0118** [comment]
> Changing lines 45:64 of vul_preprocess.py to:
> 
> ```
> def load_graphs(args):
>     #csv_file = os.path.join(args.csv_dir, "function.csv")
>     json_file = os.path.join(args.csv_dir, "function.json") 
>     paths = []
>     #df = pd.read_csv(csv_file, header=0, index_col=False)
>     df = pd.read_json(json_file)
>     id2sha = df.to_dict()['commit_id']
>     id2tgt = df.to_dict()['target']
>     idx = [str(i) for i in id2sha.keys()]
> 
>         
>     #with open(os.path.join(args.file_list), "r") as f:
>     #    idx = [str(i.strip()) for i in f.readlines()]
> 
>     for i in range(0, len(idx)):
>         id = idx[i]
>         path = os.path.join(args.asm_dir, str(id)+ "_" + id2sha[int(id)] + ".s")
>         if os.path.isfile(path):
>             paths.append(
>                 (i, path, id2tgt[int(id)]))
> 
>     graphs_asm = {}
>     large_asm  = {}
>     tgt_asm = {}
> ```
> 
> worked for me (the data is there is just a json instead of a csv)

Thanks for the help! I will update the name of the file.
