### ISSUE TITLE
Can't train in a PC with no GPU

### ISSUE THREAD

**Issue by MCCTT** [facebookresearch/nbref#7]
For device = cpu it fails because it tries to run: self.scale.cuda()
in encoder_decoder_layers and transformer_tree_model
self.scale is already set to_device this ".cuda()" shouldn't be needed
To reproduce try training in a machine with no GPU
---> cd baseline_model && python run_similarity_check.py

**Comment by ChengFu0118** [comment]
For multiple device training, remove `cuda()` will result in node mismatch. If you train it on cpu, you can simply remove it or check the training device first. Actually, I never tried to train the model on CPU-only.
